version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ca-central-1:495599735553:task-definition/product-task-def:7"
        LoadBalancerInfo:
          ContainerName: "product-service-container"
          ContainerPort: 3001
