version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 495599735553.dkr.ecr.ca-central-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t product-service ./product-service
      - docker tag product-service:latest 495599735553.dkr.ecr.ca-central-1.amazonaws.com/product-service:latest

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 495599735553.dkr.ecr.ca-central-1.amazonaws.com/product-service:latest
      - printf '[{"name":"product-service","imageUri":"%s"}]' 495599735553.dkr.ecr.ca-central-1.amazonaws.com/product-service:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
